package com.soft2bet.model

case class PlayerSegmentation(
    player_id: Option[String],
    brand_id: Option[String],
    RFM_APR_ACTIVITY: Option[String],
    RFM_APR_VALUE: Option[String],
    RFM_APR_MONETARY: Option[String],
    RFM_APR_ORIENTATION: Option[String],
    RFM_APR_NEW_SEGMENT: Option[String],
    RFM_APR_RUNDAY: Option[String],
    PROB: Option[String],
    BUCKET1_HIGH_CHANCE_TO_CONVERT: Option[String],
    BUCKET2_MEDIUM_CHANCE_TO_CONVERT: Option[String],
    BUCKET3_LOW_CHANCE_TO_CONVERT: Option[String],
    PREDICTION_DAY: Option[String],
    TrafficGroup: Option[String],
    TrafficType: Option[String],
    Sport_GGR_1d: Option[String],
    Sport_TO_1d: Option[String],
    Sport_Bonus_GGR_1d: Option[String],
    Sport_GGR_7d: Option[String],
    Sport_TO_7d: Option[String],
    Sport_Bonus_GGR_7d: Option[String],
    Sport_GGR_30d: Option[String],
    Sport_TO_30d: Option[String],
    Sport_Bonus_GGR_30d: Option[String],
    ACCOUNT_IDT: Option[String],
    ACTIVITY_SEGMENT: Option[String],
    DEPOSIT_SEGMENT: Option[String],
    NGR_SEGMENT: Option[String],
    ACQUISITION_SEGMENT: Option[String],
    LT_MODE_DEPOSITS: Option[String],
    PRODUCT_SEGMENT: Option[String],
    RECORD_UPDATED: Option[String],
    DEPOSIT_SEGMENT_RANGE: Option[String],
    DEPOSIT_SEGMENT_MODE_DIST: Option[String],
    NGR_SEGMENT_RANGE: Option[String],
    LT_NGR_SEGMENT: Option[String],
    LT_NGR_SEGMENT_RANGE: Option[String],
    LT_PRODUCT_SEGMENT: Option[String],
    RECORD_CREATED: Option[String],
    UNIQUEID: Option[String],
    NEXT_BEST_BRAND: Option[String],
    FREE_BONUS_ABUSER: Option[String],
    ZBR_brand_id: Option[String],
    ZBR_player_id: Option[String],
    ZBR_predition_date: Option[String],
    ZBR_ltv_prediction: Option[String],
    ZBR_ltv_ggr_top_prediction: Option[String],
    ZBR_ltv_ggr_prediction: Option[String],
    ZBR_days_from_registration: Option[String],
    ZBR_current_activity_days: Option[String],
    ZBR_churn_prediction: Option[String],
    CROSS_ACTIVITY_STATUS: Option[String],
)

case class PlayerSegmentationSQS(
    player_id: Option[String],
    brand_id: Option[String],
    RFM_APR_ACTIVITY: Option[String],
    RFM_APR_VALUE: Option[String],
    RFM_APR_MONETARY: Option[String],
    RFM_APR_ORIENTATION: Option[String],
    RFM_APR_NEW_SEGMENT: Option[String],
    RFM_APR_RUNDAY: Option[String],
    PROB: Option[String],
    BUCKET1_HIGH_CHANCE_TO_CONVERT: Option[String],
    BUCKET2_MEDIUM_CHANCE_TO_CONVERT: Option[String],
    BUCKET3_LOW_CHANCE_TO_CONVERT: Option[String],
    PREDICTION_DAY: Option[String],
    trafficgroup: Option[String],
    traffictype: Option[String],
    Sport_GGR_1d: Option[String],
    Sport_TO_1d: Option[String],
    Sport_Bonus_GGR_1d: Option[String],
    Sport_GGR_7d: Option[String],
    Sport_TO_7d: Option[String],
    Sport_Bonus_GGR_7d: Option[String],
    Sport_GGR_30d: Option[String],
    Sport_TO_30d: Option[String],
    Sport_Bonus_GGR_30d: Option[String],
    ACCOUNT_IDT: Option[String],
    ACTIVITY_SEGMENT: Option[String],
    DEPOSIT_SEGMENT: Option[String],
    NGR_SEGMENT: Option[String],
    ACQUISITION_SEGMENT: Option[String],
    LT_MODE_DEPOSITS: Option[String],
    PRODUCT_SEGMENT: Option[String],
    RECORD_UPDATED: Option[String],
    DEPOSIT_SEGMENT_RANGE: Option[String],
    DEPOSIT_SEGMENT_MODE_DIST: Option[String],
    NGR_SEGMENT_RANGE: Option[String],
    LT_NGR_SEGMENT: Option[String],
    LT_NGR_SEGMENT_RANGE: Option[String],
    LT_PRODUCT_SEGMENT: Option[String],
    RECORD_CREATED: Option[String],
    UNIQUEID: Option[String],
    NEXT_BEST_BRAND: Option[String],
    FREE_BONUS_ABUSER: Option[String],
    ZBR_brand_id: Option[String],
    ZBR_player_id: Option[String],
    ZBR_predition_date: Option[String],
    ZBR_ltv_prediction: Option[String],
    ZBR_ltv_ggr_top_prediction: Option[String],
    ZBR_ltv_ggr_prediction: Option[String],
    ZBR_days_from_registration: Option[String],
    ZBR_current_activity_days: Option[String],
    ZBR_churn_prediction: Option[String],
    CROSS_ACTIVITY_STATUS: Option[String],
)

object PlayerSegmentationSQS {
  import io.circe.Encoder
  import io.circe.generic.semiauto._
  implicit val playerSegmentationSQSEncoder: Encoder[PlayerSegmentationSQS] =
    deriveEncoder

  def apply(
      playerSegmentation: PlayerSegmentation
  ): PlayerSegmentationSQS = {
    PlayerSegmentationSQS(
      player_id = playerSegmentation.player_id,
      brand_id = playerSegmentation.brand_id,
      RFM_APR_ACTIVITY = playerSegmentation.RFM_APR_ACTIVITY,
      RFM_APR_VALUE = playerSegmentation.RFM_APR_VALUE,
      RFM_APR_MONETARY = playerSegmentation.RFM_APR_MONETARY,
      RFM_APR_ORIENTATION = playerSegmentation.RFM_APR_ORIENTATION,
      RFM_APR_NEW_SEGMENT = playerSegmentation.RFM_APR_NEW_SEGMENT,
      RFM_APR_RUNDAY = playerSegmentation.RFM_APR_RUNDAY,
      PROB = playerSegmentation.PROB,
      BUCKET1_HIGH_CHANCE_TO_CONVERT =
        playerSegmentation.BUCKET1_HIGH_CHANCE_TO_CONVERT,
      BUCKET2_MEDIUM_CHANCE_TO_CONVERT =
        playerSegmentation.BUCKET2_MEDIUM_CHANCE_TO_CONVERT,
      BUCKET3_LOW_CHANCE_TO_CONVERT =
        playerSegmentation.BUCKET3_LOW_CHANCE_TO_CONVERT,
      PREDICTION_DAY = playerSegmentation.PREDICTION_DAY,
      trafficgroup = playerSegmentation.TrafficGroup,
      traffictype = playerSegmentation.TrafficType,
      Sport_GGR_1d = playerSegmentation.Sport_GGR_1d,
      Sport_TO_1d = playerSegmentation.Sport_TO_1d,
      Sport_Bonus_GGR_1d = playerSegmentation.Sport_Bonus_GGR_1d,
      Sport_GGR_7d = playerSegmentation.Sport_GGR_7d,
      Sport_TO_7d = playerSegmentation.Sport_TO_7d,
      Sport_Bonus_GGR_7d = playerSegmentation.Sport_Bonus_GGR_7d,
      Sport_GGR_30d = playerSegmentation.Sport_GGR_30d,
      Sport_TO_30d = playerSegmentation.Sport_TO_30d,
      Sport_Bonus_GGR_30d = playerSegmentation.Sport_Bonus_GGR_30d,
      ACCOUNT_IDT = playerSegmentation.ACCOUNT_IDT,
      ACTIVITY_SEGMENT = playerSegmentation.ACTIVITY_SEGMENT,
      DEPOSIT_SEGMENT = playerSegmentation.DEPOSIT_SEGMENT,
      NGR_SEGMENT = playerSegmentation.NGR_SEGMENT,
      ACQUISITION_SEGMENT = playerSegmentation.ACQUISITION_SEGMENT,
      LT_MODE_DEPOSITS = playerSegmentation.LT_MODE_DEPOSITS,
      PRODUCT_SEGMENT = playerSegmentation.PRODUCT_SEGMENT,
      RECORD_UPDATED = playerSegmentation.RECORD_UPDATED,
      DEPOSIT_SEGMENT_RANGE = playerSegmentation.DEPOSIT_SEGMENT_RANGE,
      DEPOSIT_SEGMENT_MODE_DIST = playerSegmentation.DEPOSIT_SEGMENT_MODE_DIST,
      NGR_SEGMENT_RANGE = playerSegmentation.NGR_SEGMENT_RANGE,
      LT_NGR_SEGMENT = playerSegmentation.LT_NGR_SEGMENT,
      LT_NGR_SEGMENT_RANGE = playerSegmentation.LT_NGR_SEGMENT_RANGE,
      LT_PRODUCT_SEGMENT = playerSegmentation.LT_PRODUCT_SEGMENT,
      RECORD_CREATED = playerSegmentation.RECORD_CREATED,
      UNIQUEID = playerSegmentation.UNIQUEID,
      NEXT_BEST_BRAND =
        playerSegmentation.NEXT_BEST_BRAND.filterNot(_ == "NULL"),
      FREE_BONUS_ABUSER =
        playerSegmentation.FREE_BONUS_ABUSER.filterNot(_ == "NULL"),
      ZBR_brand_id = playerSegmentation.ZBR_brand_id,
      ZBR_player_id = playerSegmentation.ZBR_player_id,
      ZBR_predition_date = playerSegmentation.ZBR_predition_date,
      ZBR_ltv_prediction = playerSegmentation.ZBR_ltv_prediction,
      ZBR_ltv_ggr_top_prediction =
        playerSegmentation.ZBR_ltv_ggr_top_prediction,
      ZBR_ltv_ggr_prediction = playerSegmentation.ZBR_ltv_ggr_prediction,
      ZBR_days_from_registration =
        playerSegmentation.ZBR_days_from_registration,
      ZBR_current_activity_days = playerSegmentation.ZBR_current_activity_days,
      ZBR_churn_prediction = playerSegmentation.ZBR_churn_prediction,
      CROSS_ACTIVITY_STATUS = playerSegmentation.CROSS_ACTIVITY_STATUS
    )
  }
}
