package com.jada.models

import scala.util.Try

case class PlayerBatchJsonSQS(
    brand_id: Option[String] = None,
    brand_description: Option[String] = None,
    reg_date: Option[String] = None,
    firstName: Option[String] = None,
    lastName: Option[String] = None,
    emailAddress: Option[String] = None,
    mobileNumber: Option[String] = None,
    language: Option[String] = None,
    affiliate_id: Option[String] = None,
    dob: Option[String] = None,
    country_description: Option[String] = None,
    currency_description: Option[String] = None,
    account_status: Option[String] = None,
    vip_status: Option[String] = None,
    login_name: Option[String] = None,
    domain_url: Option[String] = None,
    gender: Option[String] = None,
    mobile_status: Option[String] = None,
    email_verified: Option[String] = None,
    la_bcasinocom: Option[String] = None,
    la_boocasino: Option[String] = None,
    la_boocasinoca: Option[String] = None,
    la_galacticwins: Option[String] = None,
    la_mrfortune: Option[String] = None,
    marketing_seg: Option[String] = None,
    total_bonus_given: Option[String] = None,
    total_wd_amount: Option[String] = None,
    avg_deposit: Option[String] = None,
    avg_bet: Option[String] = None,
    avg_bet_eur: Option[String] = None,
    favorite_game: Option[String] = None,
    fav_game_cat: Option[String] = None,
    bonus_ratio: Option[String] = None,
    wd_ratio: Option[String] = None,
    turnover_ratio: Option[String] = None,
    ngr: Option[String] = None,
    chargeback: Option[String] = None,
    vip_seg: Option[String] = None,
    bonus_optout: Option[String] = None,
    total_number_of_deposits: Option[String] = None,
    total_deposit_amount: Option[String] = None,
    last_game_played: Option[String] = None,
    total_balance: Option[String] = None,
    bonus_balance: Option[String] = None,
    cp_balance: Option[String] = None,
    ftd_date: Option[String] = None,
    last_deposit_date: Option[String] = None,
    last_bonus_given: Option[String] = None,
    last_login_date: Option[String] = None,
    pending_withdrawal: Option[String] = None,
    pending_withdrawal_euro: Option[String] = None,
    total_deposit_amount_eur: Option[String] = None,
    total_bonus_given_eur: Option[String] = None,
    total_balance_eur: Option[String] = None,
    bonus_balance_eur: Option[String] = None,
    total_wd_amount_eur: Option[String] = None,
    avg_deposit_eur: Option[String] = None,
    cp_accumulated: Option[String] = None,
    id_status: Option[String] = None,
    poa_status: Option[String] = None
)

object PlayerBatchJsonSQS {

  import io.circe.Encoder
  import io.circe.generic.semiauto._

  def apply(ps: PlayerStore): PlayerBatchJsonSQS = {
    PlayerBatchJsonSQS(
      brand_id = ps.brand_id,
      brand_description = ps.brand_description,
      reg_date = ps.reg_datetime.map(x => Try(x.substring(0, 10)).getOrElse(x)),
      firstName = ps.first_name,
      lastName = ps.last_name,
      emailAddress = ps.email,
      mobileNumber = ps.phone_number,
      language = ps.language,
      affiliate_id = ps.affiliate_id,
      dob = ps.dob.map(x => Try(x.substring(0, 10)).getOrElse(x)),
      country_description = ps.country_description,
      currency_description = ps.currency_description,
      account_status = ps.account_status,
      vip_status = ps.vip_status,
      login_name = ps.login_name,
      domain_url = ps.domain_url,
      gender = ps.gender,
      mobile_status = ps.mobile_status,
      email_verified = ps.email_verified,
      la_bcasinocom = ps.la_bcasinocom,
      la_boocasino = ps.la_boocasino,
      la_boocasinoca = ps.la_boocasinoca,
      la_galacticwins = ps.la_galacticwins,
      la_mrfortune = ps.la_mrfortune,
      marketing_seg = ps.marketing_seg,
      total_bonus_given = ps.total_bonus_given,
      total_wd_amount = ps.total_wd_amount,
      avg_deposit = ps.avg_deposit,
      avg_bet = ps.avg_bet,
      avg_bet_eur = ps.avg_bet_eur,
      favorite_game = ps.favorite_game,
      fav_game_cat = ps.fav_game_cat,
      bonus_ratio = ps.bonus_ratio,
      wd_ratio = ps.wd_ratio,
      turnover_ratio = ps.turnover_ratio,
      ngr = ps.ngr,
      chargeback = ps.chargeback,
      vip_seg = ps.vip_seg,
      bonus_optout = ps.bonus_optout,
      total_number_of_deposits = ps.total_number_of_deposits,
      total_deposit_amount = ps.total_deposit_amount,
      last_game_played = ps.last_game_played,
      total_balance = ps.total_balance,
      bonus_balance = ps.bonus_balance,
      cp_balance = ps.cp_balance,
      ftd_date = ps.ftd_date,
      last_deposit_date = ps.last_deposit_date,
      last_bonus_given = ps.last_bonus_given,
      last_login_date = ps.last_login_date,
      pending_withdrawal = ps.pending_withdrawal,
      pending_withdrawal_euro = ps.pending_withdrawal_euro,
      total_deposit_amount_eur = ps.total_deposit_amount_eur,
      total_bonus_given_eur = ps.total_bonus_given_eur,
      total_balance_eur = ps.total_balance_eur,
      bonus_balance_eur = ps.bonus_balance_eur,
      total_wd_amount_eur = ps.total_wd_amount_eur,
      avg_deposit_eur = ps.avg_deposit_eur,
      cp_accumulated = ps.cp_accumulated,
      id_status = ps.id_status,
      poa_status = ps.poa_status
    )
  }

  implicit val batchPlayerSQSEncoder: Encoder[PlayerBatchJsonSQS] =
    deriveEncoder
}
