set allow-duplicate-variables 

registry := "centralregistry"

login:
  # Authenticate to {{registry}}
  @az acr login -n {{registry}} > /dev/null

push profile: login
  # Push image with profile {{profile}}
  @./gradlew clean imagePush -Dquarkus.profile={{profile}} -x test 


mvn-push profile: login
  # Push image with profile {{profile}}
  mvn clean package -U -DskipTests -Dquarkus.profile={{profile}} -f {{invocation_directory()}}/pom.xml

mvn-function:
  # deploy functions
  mvn clean package azure-functions:deploy -Pjada -f {{invocation_directory()}}/pom.xml -s ${MVN_SETTINGS:-${HOME}/.m2/settings.xml}

aca-replicas:
  # This command is slow as it makes a separate API call for each container app.
  # It lists the name, resource group, and the current number of replicas.
  @az containerapp list --query "[].{name:name, resourceGroup:resourceGroup}" -o tsv | while read -r name resourceGroup; do \
    replicas=$(az containerapp replica count --name "$name" --resource-group "$resourceGroup"); \
    printf "%-30s%-20s%-10s\n" "$name" "$resourceGroup" "$replicas"; \
  done
